# Numpy Arrays

In [1]:
import numpy as np

In [2]:
x= np.array([4,5,6,7])

In [3]:
x+1

array([5, 6, 7, 8])

In [4]:
y= np.array([1,2,3,4])

In [7]:
x+y

array([ 5,  7,  9, 11])

# Matrix Multiplication

In [6]:
np.dot(x,y)

60

In [8]:
x==y

array([False, False, False, False])

In [9]:
x=x/10

In [10]:
x

array([0.4, 0.5, 0.6, 0.7])

In [13]:
y

array([1, 2, 3, 4])

# Universal Functions of Numpy

In [15]:
np.square(x)

array([0.16, 0.25, 0.36, 0.49])

In [17]:
np.log(x)

array([-0.91629073, -0.69314718, -0.51082562, -0.35667494])

In [19]:
np.arcsin(1)

1.5707963267948966

In [20]:
np.rad2deg(2)

114.59155902616465

In [21]:
np.mod(x,y)

array([0.4, 0.5, 0.6, 0.7])

In [22]:
np.mod(y,x)

array([2.00000000e-01, 0.00000000e+00, 1.11022302e-16, 5.00000000e-01])

# Reshape Function

In [31]:
x = np.array([1,2,3,4,5])

In [32]:
z = np.repeat(x,3).reshape(5,3)

In [33]:
z

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4],
       [5, 5, 5]])

In [34]:
np.median(z)

3.0

In [35]:
np.median(z,axis=0)

array([3., 3., 3.])

In [36]:
np.median(z,axis=1)

array([1., 2., 3., 4., 5.])

In [37]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [38]:
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

# Broadcasting and Shape Manipulation

In [39]:
x=np.array([[0,0,0],[10,10,10],[20,20,20]])

In [40]:
y=np.array([1,2,3])

In [41]:
x+y

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [42]:
x = np.array([[0],[10],[20]])

In [43]:
x

array([[ 0],
       [10],
       [20]])

In [44]:
x+y

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

# Reshaping Numpy Arrays

In [45]:
x=np.arange(24)

In [46]:
x.shape = 2,3,-1

In [47]:
x

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Vector Stacking

In [48]:
x= np.arange(0,10,2)

In [49]:
y = np.arange(0,-5,-1)

In [51]:
np.vstack([x,y])

array([[ 0,  2,  4,  6,  8],
       [ 0, -1, -2, -3, -4]])

In [52]:
np.hstack([x,y])

array([ 0,  2,  4,  6,  8,  0, -1, -2, -3, -4])

In [53]:
np.dstack([x,y])

array([[[ 0,  0],
        [ 2, -1],
        [ 4, -2],
        [ 6, -3],
        [ 8, -4]]])

# Boolean Mask

In [54]:
x=np.array([1,3,-1,5,7,-1])

In [55]:
mask=(x<0)

In [56]:
mask

array([False, False,  True, False, False,  True])

In [57]:
x[mask]=0

In [58]:
x

array([1, 3, 0, 5, 7, 0])