# Matrix Class

In [1]:
import numpy as np
ndarray=np.arange(9).reshape(3,3)

matrix func - It creates a copy

In [2]:
x=np.matrix(ndarray)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


mat func - It changes the view only i.e. numpy.matrix(data, copy=False) 

In [3]:
#it returns a 3*3 identity array
y=np.mat(np.identity(3))
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Matrix Operations

Addition operation

In [4]:
print(x+y)

[[1. 1. 2.]
 [3. 5. 5.]
 [6. 7. 9.]]


Multiplication operation

In [5]:
print(x*x)

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


dot func - It is used to multiply the two matrices

In [6]:
print(x.dot(ndarray, ndarray))

[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [7]:
print(x**3)
#** is used as a power notation 

[[ 180  234  288]
 [ 558  720  882]
 [ 936 1206 1476]]


Inverse of a matrix

In [8]:
z=np.matrix(np.random.randint(1,50,9).reshape(3,3))
print(z)
#inverse - I is used to determine the inverse of a matrix
print(z.I)

[[24 46 41]
 [37 22  5]
 [ 9 25 35]]
[[-0.05281258  0.04789978  0.05502334]
 [ 0.10234995 -0.03856546 -0.11438631]
 [-0.05952673  0.01522967  0.09612708]]


Transpose of a matrix

In [9]:
#transpose - H is used to determine the transpose of a matrix
print(z.H)

[[24 37  9]
 [46 22 25]
 [41  5 35]]


# Solving AX=B

We have a linear equation ax=b and we have to determine the value of x
#x=A-1B

In [10]:
A=np.mat('3,1,4; 1,5,9; 2,6,5')
b=np.mat([[1], [2], [3]])
x=A.I*b
print(x)

[[ 0.26666667]
 [ 0.46666667]
 [-0.06666667]]


allclose func - it coompare the LHS and RHS it returns true if LHS and RHS are equal

In [11]:
np.allclose(A*x, b)

True

# Comparison of Performance between ndarray and matrix

In [12]:
x=np.arange(25000000).reshape(5000,5000)
y=np.mat(x)
%timeit x.T
%timeit y.T

209 ns ± 5.22 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
896 ns ± 30.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


So, for transpose the matrix takes much larger time than ndarray. So, because of better performance we prefer ndarray over matrix. 

# Linear Algebra in NumPy

vdot func - It flattens input arrays first and then multiplies them

In [13]:
x=np.array([[1,2], [3,4]])
y=np.array([[10,20], [30,40]])
print(np.vdot(x, y))

300


cross func - it returns a vector perpendicular to both input data (a,b)

In [14]:
a=np.array([1,0,0])
b=np.array([0,1,0])
print(np.cross(a,b))
print(np.cross(b,a))

[0 0 1]
[ 0  0 -1]


# numpy.linalg()

determinant of a matrix

In [15]:
x=np.array([[4,8], [7,9]])
np.linalg.det(x)

-20.000000000000007

inverse of a matrix

In [16]:
print(np.linalg.inv(x))

[[-0.45  0.4 ]
 [ 0.35 -0.2 ]]


solve Ax=b

In [17]:
x=np.linalg.solve(A,b)
print(x)

[-0.21111111 -0.07777778  0.17777778]


# Decomposition

determine eigenvalues and eigenvectors

In [18]:
x=np.random.randint(0,10,9).reshape(3,3)
w, v=np.linalg.eig(x)
#eigenvalues
print(w)
#eigenvectors
print(v)

[13.68566918+0.j          5.15716541+4.15272508j  5.15716541-4.15272508j]
[[ 0.42956536+0.j          0.25518515+0.27576356j  0.25518515-0.27576356j]
 [ 0.60441836+0.j          0.13257752-0.58235907j  0.13257752+0.58235907j]
 [ 0.67093372+0.j         -0.70860152+0.j         -0.70860152-0.j        ]]


if the input ndarray is complex valued the computed eigen vectors would be the complex

In [19]:
y=np.array([[1,2j], [-3j,4]])
print(np.linalg.eig(y))

(array([-0.37228132+0.j,  5.37228132+0.j]), array([[ 0.82456484+0.j        , -0.        +0.41597356j],
       [-0.        +0.56576746j,  0.90937671+0.j        ]]))


# SVD

In [20]:
np.set_printoptions(precision=4)
A=np.array([3,1,4,1,5,9,2,6,5]).reshape(3,3)
u, sigma, vh=np.linalg.svd(A)
#u stands for the left singular vectors of A (eigenvectors of AA-1)
print(u)
#vh stands for the inverse matrix of right singular vectors of A (eigenvectors of (A-1A)-1)
print(vh)
#sigma is the no zeros singular values of A (eigenvalues of both AA-1 and A-1A)
print(sigma)

[[-0.3246  0.799   0.5062]
 [-0.7531  0.1055 -0.6494]
 [-0.5723 -0.592   0.5675]]
[[-0.2114 -0.5539 -0.8053]
 [ 0.4633 -0.7822  0.4164]
 [ 0.8606  0.2851 -0.422 ]]
[13.5824  2.8455  2.3287]


In [21]:
#now verify the results
diag_sigma=np.diag(sigma)
Av=u.dot(diag_sigma).dot(vh)
np.allclose(A,Av)

True

# QR Decomposition

In [22]:
#solve Ax=b
b=np.array([1,2,3]).reshape(3,1)
q, r=np.linalg.qr(A)
x=np.dot(np.linalg.inv(r), np.dot(q.T, b))
print(x)

[[ 0.2667]
 [ 0.4667]
 [-0.0667]]


# Polynomial Mathematics

Calculate the coefficient of polynomial

In [23]:
#here gives the root of the equation
root=np.array([1,2,3,4])
print(np.poly(root))

[  1. -10.  35. -50.  24.]


Calculating the roots of the equation

In [24]:
#here gives the coefficient of the equation
print(np.roots([1,-10,35,-50,24]))

[4. 3. 2. 1.]


polyval func - We have a equation y=x4-10x3+35x2-50x+24 and we want to find the value of y on some x

In [25]:
print(np.polyval(([1,-10,35,-50,24]), 5))

24


Integrals and Derivatives

In [26]:
coef=np.array([1,-10,35,-50,24])
#polyint func is used to find the integral of a equation
integral=np.polyint(coef)
print(integral)
#polyder func is used to find the derivative of a equation
print(np.polyder(integral)==coef)
print(np.polyder(coef, 5))

[  0.2     -2.5     11.6667 -25.      24.       0.    ]
[ True  True  True  True  True]
[]


Polynomial class

In [27]:
from numpy.polynomial import polynomial
p=polynomial.Polynomial(coef)
print(p)

poly([  1. -10.  35. -50.  24.])


In [28]:
#coefficient of a equation
print(p.coef)
#roots of a equation
print(p.roots())

[  1. -10.  35. -50.  24.]
[0.25   0.3333 0.5    1.    ]


In [29]:
#the value returned by equation on a particular x
print(polynomial.polyval(p, 5))

poly([5.])


In [30]:
#integral and derivative
print(p.integ())
print(p.integ().deriv()==p)

poly([  0.       1.      -5.      11.6667 -12.5      4.8   ])
True


# Regression and Curve Fitting

The relationship between the age of a person and his sleeping quality
#we use 100 as our total population and simulate the age and sleeping scores followed the same distribution as the survey results

In [31]:
#it simulate the real age among our 100 population to see the age variable
groups=[7, 24, 21, 19, 17, 12]
age=np.concatenate([np.random.randint((ind+1)*10, (ind+2)*10, group) for ind, group in enumerate(groups)])
print(age)

[11 16 15 18 10 12 19 23 24 25 29 28 22 29 25 24 21 24 22 29 29 21 26 29
 28 26 27 28 23 27 23 33 35 31 37 30 34 34 30 33 37 39 36 39 30 30 33 30
 33 38 36 33 42 48 41 41 45 47 46 42 44 49 42 46 40 45 49 42 43 43 48 56
 50 53 55 51 55 50 54 59 55 52 53 58 52 50 53 57 60 61 65 60 64 61 68 63
 63 62 60 66]


In [32]:
#it simulate the score distribution
scores=[5.5, 5.7, 5.4, 4.9, 4.6, 4.4]
sim_scores=np.concatenate([.01*np.random.rand(group)+scores[ind] for ind, group in enumerate(groups)])
print(sim_scores)

[5.504  5.5041 5.5068 5.5035 5.509  5.508  5.5072 5.7084 5.7038 5.7078
 5.7009 5.7087 5.7053 5.7053 5.7017 5.7063 5.7055 5.7006 5.7096 5.7073
 5.7057 5.7065 5.702  5.7052 5.708  5.7052 5.7029 5.7061 5.7079 5.7084
 5.7032 5.4062 5.4005 5.4024 5.4079 5.4035 5.4024 5.4066 5.4071 5.4013
 5.41   5.4003 5.4052 5.4018 5.4058 5.4094 5.4022 5.41   5.4071 5.4024
 5.4079 5.4098 4.9015 4.9087 4.9022 4.9042 4.9009 4.9057 4.9092 4.9078
 4.9006 4.9055 4.9075 4.9039 4.9011 4.9001 4.9068 4.901  4.9008 4.9061
 4.9054 4.6045 4.6045 4.6065 4.6063 4.6079 4.6086 4.6046 4.6021 4.6078
 4.602  4.6019 4.6097 4.6064 4.6083 4.6066 4.6063 4.6031 4.4076 4.4078
 4.4029 4.4041 4.4027 4.4051 4.404  4.4021 4.4075 4.4028 4.4047 4.4031]


lstsq func - The numpy function for the regression line is numpy.linalg.lstsq() and it takes the coefficient matrix and dependent variable values as input

In [33]:
AGE=np.vstack([age, np.ones(len(age))]).T
m, c=np.linalg.lstsq(AGE, sim_scores)[0]
#slope
print(m)
#constant
print(c)

-0.030680614597938274
6.3398174057997645


/srv/conda/envs/notebook/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  


The two degree relation - the housing price by year

In [34]:
year=np.arange(1,11)
price=np.array([129000, 133000, 138000, 144000, 142000, 141000, 150000, 135000, 134000, 139000])

polyfit func - it help us to find the coefficient of polynomial equation

In [35]:
a, b, c=np.polyfit(year, price, 2)
print(a)
print(b)
print(c)

-549.2424242424238
6641.6666666666515
123116.66666666663
