# NumPy Array

In [1]:
import numpy as np
x=np.array([[1,2,3],[2,3,4]])
print(x)

[[1 2 3]
 [2 3 4]]


Calculating the dimensionality of array

In [2]:
print(x.ndim)

2


Checking the shape attribute of array

In [3]:
print(x.shape)

(2, 3)


# Indexing

In [4]:
#initialize a random numpy array
x=np.random.random((100,100))
y=x[42,87]
print(y)

0.24287662870733473


# Slicing

Printing the entire row

In [5]:
print(x[1,:])

[0.81051135 0.70283671 0.45857007 0.18443466 0.20401009 0.83476037
 0.7364204  0.81993903 0.59888261 0.08964136 0.29486861 0.07161877
 0.30542222 0.33207774 0.18710298 0.96842831 0.69416053 0.53474516
 0.84461786 0.19322689 0.70434082 0.36480161 0.31358721 0.0630457
 0.90002469 0.53552892 0.2380357  0.15397737 0.76838426 0.72482513
 0.8365651  0.41892197 0.98299845 0.0634112  0.51069894 0.49976818
 0.62167408 0.06961761 0.98006477 0.30019093 0.06976415 0.26694873
 0.34339825 0.39120436 0.21574783 0.33460686 0.66443396 0.45070076
 0.75595121 0.10102469 0.68502862 0.14077255 0.10762171 0.07087541
 0.17728359 0.53843408 0.95952896 0.13230325 0.21865109 0.53264974
 0.15506035 0.33488857 0.1080867  0.79986114 0.3684402  0.81748947
 0.89142193 0.53284465 0.95142424 0.72103013 0.28739152 0.84792594
 0.58195282 0.38199139 0.78005188 0.32389949 0.13983541 0.45018552
 0.18396008 0.65775232 0.4262598  0.95767677 0.97740703 0.9498251
 0.50971005 0.95012758 0.92384596 0.52217411 0.09152272 0.817672

printing the entire column

In [6]:
print(x[:,1])

[0.28849714 0.70283671 0.56386662 0.66402599 0.03688342 0.7001077
 0.12337325 0.89977861 0.47305475 0.25552894 0.32349731 0.13362901
 0.89181075 0.04732534 0.63453864 0.49072656 0.92456724 0.10263745
 0.88875381 0.08624202 0.65407938 0.59609404 0.09052058 0.44492693
 0.39527818 0.20612035 0.31187579 0.41268487 0.62754579 0.64462176
 0.85287414 0.07465476 0.30891717 0.16802494 0.42056288 0.27600526
 0.83026255 0.82100482 0.64626605 0.36719727 0.26753528 0.34909199
 0.40100782 0.52756387 0.99616165 0.28987829 0.13493109 0.67638164
 0.28199736 0.74679444 0.87716551 0.9067166  0.41528361 0.84917937
 0.52302861 0.34765781 0.10874664 0.38426453 0.27314276 0.15655958
 0.50641523 0.81504811 0.65354687 0.66960331 0.91521913 0.15637795
 0.18150022 0.99642332 0.80738917 0.0012155  0.04824205 0.00104541
 0.62388872 0.68648518 0.62445068 0.6533253  0.61633282 0.40057321
 0.01137289 0.0841442  0.63914126 0.70276119 0.34012096 0.3803711
 0.81857497 0.34188106 0.14826022 0.85643201 0.42100893 0.095225

Reversing array

In [7]:
print(x[::-1])

[[0.2183444  0.67455439 0.42124504 ... 0.59669834 0.64496154 0.8008802 ]
 [0.54128272 0.45608274 0.80198922 ... 0.90125176 0.88225027 0.46507622]
 [0.33351915 0.3791437  0.06291108 ... 0.08519697 0.95028106 0.38256701]
 ...
 [0.35787833 0.56386662 0.64657218 ... 0.63304177 0.30381584 0.6749126 ]
 [0.81051135 0.70283671 0.45857007 ... 0.96859691 0.5193624  0.8686846 ]
 [0.10702829 0.28849714 0.07782029 ... 0.87793455 0.9338004  0.44176147]]


# Memory Layout of ndarray

The flags layout holds memory information about the array

In [8]:
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

#C_CONTIGUOUS means row major indexing of array.
#F_CONTIGUOUS means column major indexing of array.
#Let's take a example on both types of indexing.

In [9]:
c_array=np.random.rand(10, 10)
f_array=np.asfortranarray(c_array)
#return the sum of zeroth row
def sum_row(x):
    return np.sum(x[0, :])
#return the sum of zeroth column
def sum_col(x):
    return np.sum(x[:, 0])

#the summing up the row of a C array is much faster than summing up its column because in C array elements in a row are laid in successive locations.
#the opposite is true for Fortran array where the elements of a column are laid in a consecutive memory locations.
%timeit sum_row(c_array)
%timeit sum_row(f_array)
%timeit sum_col(c_array)
%timeit sum_col(f_array)

4.97 µs ± 144 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
5.52 µs ± 635 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
5.22 µs ± 456 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
5.21 µs ± 383 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Views

In [10]:
x=np.random.rand(100,10)
#here y is the view of x
y=x[:5, :]
#may_share_function determine whether two arrays are view or copy of each other
print(np.may_share_memory(x,y))
y[:]=0
print(x[:5, :])

True
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Copies 

In [11]:
x=np.random.rand(100,10)
y=np.empty([5,10])
#here y is copy of x
y[:]=x[:5, :]
print(np.may_share_memory(x,y))
y[:]=0
print(x[:5, :])

False
[[0.43369492 0.28281352 0.15810621 0.12214089 0.09725263 0.45377429
  0.15221367 0.1822641  0.78315782 0.59939959]
 [0.15525792 0.00356388 0.95426132 0.46355495 0.07499991 0.35519435
  0.5478075  0.91543117 0.56013788 0.51282034]
 [0.19998085 0.39495175 0.67705726 0.16467648 0.6926108  0.97299596
  0.59086604 0.79787718 0.12444865 0.98873321]
 [0.15096105 0.35251278 0.15606111 0.20630921 0.34621725 0.79160681
  0.94241167 0.09926761 0.13862051 0.70680863]
 [0.32560901 0.73198095 0.15300499 0.93914927 0.83253529 0.23164989
  0.27008732 0.54789236 0.97907806 0.51070615]]


# Creating Random Arrays

In [12]:
#Create random arrays using rand func
x=np.random.rand(2, 2, 2)
print(x.shape)

(2, 2, 2)


In [13]:
#Create random arrays using random func
shape_tuple=(2, 3, 4)
y=np.random.random(shape_tuple)
print(y.shape)

(2, 3, 4)


But these two functions create float type of arrays.
#So, for creating integer type of array randint func is used.

In [14]:
LOW, HIGH=1, 11
SIZE=10
x=np.random.randint(LOW, HIGH, size=SIZE)
print(x)

[ 3  8  5  1  3  8  8 10  8  6]


# Array data types

In [15]:
#float datatype
x=np.random.random((10,10))
print(x.dtype)

#int datatype
x=np.array(range(10))
print(x.dtype)

#string datatype
x=np.array(['hello','world'])
print(x.dtype)

float64
int64
<U5


Create Customized datatypes
#For eg :- np.ones create a float type array but we provide a customized int datatype

In [16]:
x=np.ones((10,10), dtype=np.int)
print(x.dtype)

int64


# Vectorized Operations

In [17]:
#all the elements of array added by 1 simutaneously
x=np.array([1,2,3,4])
print(x+1)

#two numpy arrays are mutipied element by element
y=np.array([-1,2,3,0])
print(x*y)

#matrix multiplication using dot func
print(np.dot(x, y))

#comparison between two arrays
print(x==y)

[2 3 4 5]
[-1  4  9  0]
12
[False  True  True False]


# Universal Function

Square Function

In [18]:
x=np.arange(5,10)
print(np.square(x))

[25 36 49 64 81]


mod func

In [19]:
y=np.ones(5)*10
print(np.mod(y,x))

[0. 4. 3. 2. 1.]


minimum func - it compares two arrays and returns the minimum value for both

In [20]:
print(np.minimum(x,7))

[5 6 7 7 7]


min func - it returns the smallest element in the array

In [21]:
print(np.min(x))

5


repeat func - it repeats the given array n number of times and assign it to a new variable

In [22]:
z=np.repeat(x, 3).reshape(5,3)
print(z)

[[5 5 5]
 [6 6 6]
 [7 7 7]
 [8 8 8]
 [9 9 9]]


median func

In [23]:
print(np.median(z))
#axis=0 i.e. the operation is based on column
print(np.median(z, axis=0))
#axis=1 i.e. the operation is based on rows
print(np.median(z, axis=1))

7.0
[7. 7. 7.]
[5. 6. 7. 8. 9.]


accumulate func - to accumulate the result of applying add of all elements

In [24]:
print(np.add.accumulate(x))

[ 5 11 18 26 35]


multiply outer func - it multiplies the all pairs of elements from two input arrays

In [25]:
print(np.multiply.outer(x, x))

[[25 30 35 40 45]
 [30 36 42 48 54]
 [35 42 49 56 63]
 [40 48 56 64 72]
 [45 54 63 72 81]]


# Broadcasting Rules

In [26]:
x=np.array([[0,0,0], [10,10,10], [20,20,20]])
y=np.array([1,2,3])
#the x variable has of (3,3), while y has a shape of 3. But in numpy broadcasting the shape of y is translated to 3 by 1
print(x+y)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]]


# Reshaping

In [27]:
#In this example we have an array of shape (24,1) and after altering the shape attribute the shape has been changed to 2 by 3 by 4
x=np.arange(24)
x.shape=2, 3, -1
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


# Vector Stacking

It construct a two or multidimensional array by equally sized row vectors
#It has three types

In [28]:
x=np.arange(0, 10, 2)
y=np.arange(0, -5, -1)
#vstack - It construct new array by vertical stacking two arrays
print(np.vstack([x, y]))
#hstack - It combines two arrays horizontally
print(np.hstack([x, y]))
#dstack - It stacks the arrays in sequence depth-wise along the third dimension
print(np.dstack([x, y]))

[[ 0  2  4  6  8]
 [ 0 -1 -2 -3 -4]]
[ 0  2  4  6  8  0 -1 -2 -3 -4]
[[[ 0  0]
  [ 2 -1]
  [ 4 -2]
  [ 6 -3]
  [ 8 -4]]]


resize func

In [29]:
x=np.arange(3)
print(np.resize(x, (8,)))

[0 1 2 0 1 2 0 1]


# Boolean Mask

In [30]:
x=np.array([1,3,-1,5,7,-1])
mask=(x<0)
print(mask)

x[mask]=0
print(x)

x=np.random.random(50)
print((x>.5).sum())

[False False  True False False  True]
[1 3 0 5 7 0]
30
